name: firebase_sms
description: "Firebase SMS Authentication."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  go_router: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/ru.json